apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: artifactory-access
  namespace: ci
spec:
  encryptedData:
    ARTIFACTORY_ENCRYPT: AgCntZyniBjbqIKDs3ngPpSFrvw90mxhrr334eCycGHzGgIrN1KWD5DQJXk69Nof+CWO1kxQcHC/dBOBrMUlwoKGZP87vcG4RObztxrLWwnhpQysktzKXJZ9KoslVNbcSLguiWRZBu9+6SO5MsgoN6/cFSLowEcnsJjFvPLB1D8XTVKw3zN43WiA9q3pQOQNMqOK+j5hEvXQRA3gOhyXRIhnp6Znn19u/lsG3ZuMhpfcusLEblmbwjYDj4B0X8oebYZ5KbQ5Yg6iYBVQnrpklgiWeDeMctKYetb5nWaYirl3IIwFKIirSicGWOgHpi9/kDRW10iKPTVr23xIPc5NaKYgMkTzmuuKOa8tfDc4TyqIbinhw9rD+ma4D6CmI9pQOdiGJQl7x5GvyF1mciMXgu72+J+trGLqe6QBpzSXx+cCaBicPNI9YuWXjqACNyrSk1IoLJHo3X51ASHQEntbh53nKEP2KNCThHDMYWpaPlzP5fHKt7ev/OJX2XT64VNvWh7hf14WA6QbKRqnlSobQVGEbZ2VgT3GXwu84XZ9HM1b2fioqOcFFmBEA1Ss2X1IpPRHtsk4NSKIQvZucy+UYs+yGY4lQoHU6ohfiG6ZrbtTWQFlBkbdK5myGXKAbcK+W3uVYXWYNGIbKUe2JQ+P3M42l5aJwmXr50lEuIUwAtJpb+c1rFDulbsXJWFeHVhbJZRz7tDOV2G0rkrMYAyXne8kJo0dT65gs28EPzrTF6lrJFK8spOiFg==
    ARTIFACTORY_PASSWORD: AgADtMkJDMFUTXwpi165RisyfHww6uRhOFXxWi4a7iIOroEKrbYxiOOIBFJAW698+t+AJavOSAo/fJ24QMoNUrGTi9pc70TbmEzdXOS7yo3WGd11SZ/M/Xu/hhi8k7ki8KfZ2M8LvYrLUP4alm7mkeuj+8RifW2y82hFyKa5QLVwZD9B70n/A+YjQrDu1Ymb3Jrd5407L8DuqugDQpwv12LwwQrly+wbTZI7bzBZUpNJUbybkrTWUi3bb8EWvJ9jf8VGGjN9nYQBr5qCbwdB5pwig3VeVpS9dX26SJHQ+bKT3VrxU+7giYoQtwSgO0KpBn6WrzrBpLxSBI9K1S1+ala5HwphqGdTw0Jt7MdTxpWfbGv7tjJ7wWpfmPzHXcICK2XgJiefPHoIEo2HBWHscBWAWQpAVF8PdktaBvOCnelclGaY8PlVB/0RlXEjcjJnWJ4dd0Cg6wWJs8bypn4l+e0S0YVv/5qY4ft3TmCAgpm2qD9xvtgOBwg5kH0YNbP/4xc/l5kIhY57S0Cmgd+RwmlVGOyp+OFX6KiANfkYm0Lt9a6ogzJ37Z56QamP5EUyKbOixQrCQHWE/406K+PNj6q4LpKApLPMIjhkcI/09yZ0fcDr55qbVddbIT8cDvDyCPc1+GAL3sutg0q6zL/Qpaxh00XXie8/iU4jDFpDQBSPoiSEIPLj2d3bLIH9TTM625UWEaX4HrrkIL+xjDBUAAQX4lz++g==
    ARTIFACTORY_URL: AgBdAfwKfU8I8oaw3gHnRygKbqugSfKjzMrtPHzpJo7m5j6lxYJuX4vIKS4BjohQRLidhY6/q/eEqlN/dqVNUN8y8Pdw3RUgQ1udj8E9FF4OF9wNZYnNx1Hsieap2mESTCYHPPzM42Lo4Eq1/H3awv6fhqeIZZWzjjRhmNAR1zFWf2JgMgsp8rS5Bi61TI55pA7pnF7tFQHmYpbwehGqzZYAsBc7lgQs994imt1Y5v2lArhCmwXJWAj7sgD0gew4wQ4ucf5UWHF4NyzNKsQnUJb6S6L5b+Qqdmbw91rQsPMIw0yHcm69MXXT5ki5MbZV4pXGGYR7bV1nJCPuHYuaPsBlSBP5lkY816cv708D8Ljzwx1oGIyAoQdDvVFJ6TCDl0+r1g6wfd5m+NOukmtiuhMxOS45eQbzynqa+kMm5ioNRgLdo0BHiHeylWjFNxaziehPhvkF5uBhlfBhP+z8ZBLRWKn9wIQfBSV5LO7aBGIBqxZ/xjxf0xyFGsj7LegB0o4aAvm1Zin24e9Wtj56vshFPLN2zttCzvc0le9Pi3it309sq8ub8MEreScdy47+8PT9svjPIGJpTQ8OeJVFsKh5DKZBfzl4l7VFuqpRupvkRnybC3nCAMx32S04ihMHVEfK+1zOCvV4bnxaLd6qQeNaKcRrH1fbRgaRjCgA9UooPXU0bZuS1GaLH5eIc+BXmJ3vqLB0+cE++B2GRHaCfpnm1ikwxPLh2ipu2xlwPmQGlJLIEMI8WBggjA==
    ARTIFACTORY_USER: AgCrKnzqGF4XyD8WOjGZAMSetJuNcOPwWZsrdWGq+34set6jlJ9walPHktXB83GQpj83d09L94UT4r/0m3lSt8hAbmCYEA6H46IOr6i3mmkxDHtVtfYsu1cYSm4iqEmBVpeCEeTT+q7G3aqOrBSRR5M5TEynu4AEG09SbFJhBwidhRRSqIPyjausEJ53xuxPdH3pJthkXIj5yp7v5jx+5HD2o50yCfAIZrsJgTl2kn1YMD9oEg9mlu1ALgguwA0cf4vnQYDSvrbKznyO3K1f8uz7V6m6DVxhatAG3InjRFBbQbcjo8p8wMUhxaE97GR7wH+hHVj4/gMZIveQsatZuZ2PlTa6mLv4/ItRHvHht9FxX2ZhO4eY3vlCFS7x9fulizm3ohOk15Y8wahdU3uUkOlmHCVlwF6nHIOeRCatB3VFpujSUpHwL8VtIftRMAk7eU0gvxI6wp0fPMSgQlqD6CI0GFTyQfdbZ6XY6O+KHDBKN9QHYg0+JYmp9o4mhaN7moMjii2E+N+1HfhoGghgXhe58jcCgQHm/WKftMarLhmbu1U5kYMVXAwH1+VPnQiVwXy0lo8c4LjAKGvMV5Y/ggiyCFLKMxtzS1pQAjnfEkikutlEVasK7fD/1LbYeeM9X25HZfhY6c81n96O9fk7l3IB83GaV+WmSrNAAKgol+Jj/+GZxsf8HtpIAL310wQmspwqgI9sqw==
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
      creationTimestamp: null
      managedFields:
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            .: {}
            f:ARTIFACTORY_URL: {}
            f:ARTIFACTORY_USER: {}
          f:type: {}
        manager: kubectl
        operation: Update
        time: "2021-10-01T08:46:30Z"
      - apiVersion: v1
        fieldsType: FieldsV1
        fieldsV1:
          f:data:
            f:ARTIFACTORY_ENCRYPT: {}
            f:ARTIFACTORY_PASSWORD: {}
        manager: unknown
        operation: Update
        time: "2021-10-01T08:47:54Z"
      name: artifactory-access
      namespace: ci
    type: Opaque

