apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
  creationTimestamp: null
  name: git-credentials
spec:
  encryptedData:
    password: AgAPBOBd0NCim261dtxi3wHDspspKjEoP3swrqo64LYXMBD/u7LHCpQXmtV8drEnxE4mCSdHpWtCpmB7Lbgtodo6RSTma8YBuiSXi5xjwaYzIJCxsLWlxLufj2uFLKIeTpChZnEnJP2n2K+RsR1awx5kKdFAl0udlTolIBXOE05jYp/2vUfS08MMC2VFFdNPGCMsKyETYz9qS3Wi7Y4mlqn2YMAPOwZSnhgFaW1SDUA7xvCgTixMMpz8Rh7E5jmbsS1t9vi2mLATf/MXPWAbKOLWbKe2cKiH4sUrcB3MvRRG13wkUPkCv0yEuivjp5Upwmf0JkDwO3NqpfdxWTZl4i9loto1Vze8uDVgL5+27ewHBb73Rqb+JiBTI5vlvP4ZRx0HvVSbAmArPExygTVp0hKS2LCK279tr8RoStJB/a5KJ8Hs4oMWsLIp29o8Er6SucRhVklf5l9vNx67Hxao6UPc/dDF6XE1NIgcYb/p0ms1h92n26S0GUBvYD59PSTnamTQFzFYeK229Q/nKeVG4oFusJbSy0Pkr4sl5sYvBmDtXCqSB+W8ARPSNrD4VnCqJ04tpspnLbAo6HJ2+1PE5BeJkkoPytJnBqamJmKWjXmWfutdbWDvpzAm6dHuwEPT4XpVOTz6URTO5pBJT2pNtg8wbUwd3ngA6m3B7wZWlgBj/kG4pFYqAv5tT/+su6yOK+L9CsSsnspDB7wqKLbowDYbJ5mMtHr92Q4Bm8nne+uWqixwb8S8BT/C
    username: AgCp6Hg0eU9lrwMiSz4J5N80s6gYxGZe8t+wLaodQ3DQJiCXoWkvP2D+DOULl5ce4oApxKrG4T8RDP5V464n1gzXYVwpa9DWjALQeQDtYbPeQRLZeKQ3bS632T0GlijsctzxYKqYCD46aRdmU+cE2ukZCQAHHMCiiXY9qNP35IQ1fgZfjTh+iWRXSzIqGLhpOAp5Shp4HiagdofzR8ru532i4sxuqS1eA43G+iOVqmbj1OIOFktuqCczCb7XvV3wLL034QKSCCtQ6pf1B0QTi5iMknV77GJ/cIEeGoR4DZblXO6S2OlqZiulKpK3ZgtvLK/pnR+b2MwRy3tmPeQd7VhXFb5yH0h0pg33xMlznO7ahlFlBi0Q53Dd4Px2w4PhXxCNaL1N+KZ7vDPJuFA/+UvcFSh0OmRjLixtA2NwIr58XdHASmP78r8BGD60/7pJHuXkQdYzT3j53qnZkNujUP4OcTWJDQ1WYcGud8LlA80FP93ZUNflDsgYY4ML5ytFfheLDdDVo583q+Nrjy3FmyzgrgAVSV3n9zYTwei7yv5rXd8XGNNVv3ovbXAszy1xhZEW9UXUi70L3yu+bl8uuyUkPoa1WHxbGk8yiMSSY2izPaYzGia/dbojXfR2kmEPsWBdnVOes2oh8cfjnIUovdunRB1uI3kl9f11f5x5zCxkIgAuV5X4V7WzSAZqd8rOJl0G2K9B3HrB
  template:
    data: null
    metadata:
      annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"
        tekton.dev/git-0: https://github.com
      creationTimestamp: null
      name: git-credentials
    type: kubernetes.io/basic-auth

